"""added category name attribute to category model

Revision ID: a8afb61b0012
Revises: acedce8d5a51
Create Date: 2023-04-15 18:35:08.266949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8afb61b0012'
down_revision = 'acedce8d5a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['category_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
